[project]
name = "rest-proxy"
version = "0.1.0"
description = "Trading Bootcamp Rest Proxy"
requires-python = ">=3.12"
dependencies = [
    "flask",
    "python-dotenv",
    "gunicorn",
    "metagame",
]
